--- #YAML:1.0
name:               PDF-Report
version:            1.33
abstract:           A wrapper written for PDF::API2
author:
    - Andy Orr <aorr_at_cpan_dot_org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    PDF::API2:   0
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
